SELECT 
  COALESCE(NULLIF(TRIM(BUILDINGNAME), ''), ADDRESS) AS ADDRESS,
  COALESCE(NULLIF(TRIM(BEDROOMS), ''), BEDS) AS BEDS,
  BATHROOMS,
  PROPERTYTYPE,
  LIVINGAREA,
  COALESCE(NULLIF(TRIM(PRICE), ''), PRICE_1) AS PRICE,
  DAYSONZILLOW
FROM NashvilleRents01
LIMIT 1000;